global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:3000']
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:4000']